# Theme
cR="#ff2400"
cG="#00ff9f"
cM="#d600ff"
cY="#fee801"
cC="#05d9e8"
cP="#f4d5fd"

set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",*:RGB"

set -g mouse on

set -g status-position top
set -g status-justify centre
set -g status-left ""
set -g status-right ""
set -g status-style fg=${cG},bg=default

set -g window-status-current-format "#[fg=${cR},bold] ⚬ #W "
set -g window-status-format "(#I) #W"

set -g message-style "fg=${cR},bg=default"
set -g mode-style "fg=${cC},bg=default"
set -g pane-border-style "fg=${cC}"
set -g pane-active-border-style "fg=${cR}"

set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on
